//
//  archive_package.h
//  barc
//
//  Created by Charley Robinson on 1/26/17.
//

#ifndef archive_package_h
#define archive_package_h

#include <stdio.h>
#include <libavutil/rational.h>

struct archive_s;

struct archive_config_s {
  const char* source_path;
  const char* output_path;
  size_t width;
  size_t height;
  double begin_offset;
  double end_offset;
  const char* css_preset;
  const char* css_custom;
};

/**
 * Represents an individual stream archive, generated by OpenTok.
 */
void archive_alloc(struct archive_s** archive_out);
int archive_load_configuration(struct archive_s* archive,
                               struct archive_config_s* config);
int archive_main(struct archive_s* archive);
void archive_free(struct archive_s* archive);

#endif /* archive_package_h */
